[project]
name = "fl-cmeans-clustering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "pandas>=2.3.2",
    "scikit-fuzzy>=0.5.0",
    "scikit-learn>=1.7.1",
]
